services:
  - type: web
    name: job-app-api
    env: docker
    dockerfilePath: ./dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: True
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1

databases:
  - name: job-app-db
    databaseName: jobapp
    user: jobapp_user
    plan: free